### ISSUE TITLE
How to send tweaks (or custom data)?

### ISSUE THREAD

**Issue by vovajr11** [langflow-ai/langflow-embedded-chat#12]
Hi friends!

My code

```html
<langflow-chat
      chat_input_field="input"
      chat_inputs='{"input":""}'
      host_url="https://my_host"
      flow_id="customChat"
      style="position: absolute; bottom: 18px; right: 18px;"
      tweaks='{"customData": "123123"}'
    ></langflow-chat>
```

My response
<img width="236" alt="image" src="https://github.com/logspace-ai/langflow-embedded-chat/assets/41735477/89a534d2-9293-4af8-816a-3e607a7d1e28">

What am I doing wrong?

**Comment by anovazzi1** [comment]
hello @vovajr11, have you tried the new version?
