### ISSUE TITLE
Feature Request: Markdown for the bot message

### ISSUE THREAD

**Issue by damhack** [langflow-ai/langflow-embedded-chat#9]
It would be supercool if we could have Markdown rendering for the bot message in the chat window.

Especially for LLM completions that return code, tables or text formatting in markdown.

Langflow's UI chat supports markdown, so would be really good if embedded chat had the same feature.

**Comment by anovazzi1** [comment]
We are planning to add support for it, but it's not the priority right now

**Comment by anovazzi1** [comment]
I release a new version with markdown support, please take a look :)
